baseurl = "https://kaushalsubedi.com/blog/"
languageCode = "en-us"
title = "Kaushal Subedi's Blog"
theme = "hyde-x"
copyright = "© 2015 Kaushal Subedi, All Rights Reserved"
paginate = 10
paginatePath = "page"
disqusShortname = "ksubedi"
[permalinks]
    post = "/:year/:month/:day/:slug/"

[author]
    name = "Kaushal Subedi"
    email = "kaushal@subedi.co"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Random things from the head of a web developer."

    theme = "theme-base-4b"
    highlight = "sunburst"

    # Google Analytics.
    googleAnalytics = "UA-48832100-1"

    # Sidebar social links.
    github = "KSubedi" # Your Github profile ID
    googleplus = "KaushalSubedi" # Your Google+ profile ID
    facebook = "ksub3di" # Your Facebook profile ID
    twitter = "KSubediTweet" # Your Twitter profile ID

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
